# Generated by Django 4.2.4 on 2023-08-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('test_drive_timing', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_location', models.CharField(max_length=100)),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_code', models.IntegerField()),
                ('dealer_mobile', models.IntegerField(default=10)),
                ('customers', models.ManyToManyField(to='polls.customerdetails')),
            ],
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product'),
        ),
    ]
